### ISSUE TITLE
When file is executed

### ISSUE THREAD

**Issue by dethlux** [dotslashinit-sh/FileHider#2]
Hi I want to know if its possible to hide an exe in let's say an mp4 file and when someone double clicks it, it will also run the exe? Is this possible? if so can you kindly share a github repository or example demonstrating this?  Thanks.

**Comment by dotslashinit-sh** [comment]
Due to the way this project works, it is not possible to create a payload that executes an exe file (or any other executable file) when an image or a video file is opened using this program. This program makes an archive with all the input files and then embeds it into the selected file. Since these are loaded into memory as archive files (with compression), it is not possible to execute them. As long as I am aware, it is not possible to execute exe files this way unless the applications used to open this file has a serious bug. 

However, it is possible to embed small programs (JS & VB) in pdf and doc files and have them executed on opening. I am not aware of any working demonstrations of these hacks, you may have to search for this by yourself.
